# Generated by Django 5.2.7 on 2025-11-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('complete', 'Complete')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Library Event',
                'verbose_name_plural': 'Library Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibrarySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library Submission',
                'verbose_name_plural': 'Library Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['lemma'], 'verbose_name': 'Dictionary Entry', 'verbose_name_plural': 'Dictionary Entries'},
        ),
        migrations.AlterModelOptions(
            name='entryvariant',
            options={'ordering': ['alias'], 'verbose_name': 'Entry Variant', 'verbose_name_plural': 'Entry Variants'},
        ),
        migrations.AlterModelOptions(
            name='librarycategory',
            options={'ordering': ['name'], 'verbose_name': 'Library Category', 'verbose_name_plural': 'Library Categories'},
        ),
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Library Item', 'verbose_name_plural': 'Library Items'},
        ),
        migrations.AddIndex(
            model_name='dictionaryentry',
            index=models.Index(fields=['lemma'], name='core_dictio_lemma_1829d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dictionaryentry',
            index=models.Index(fields=['updated_at'], name='core_dictio_updated_7f3a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='entryvariant',
            index=models.Index(fields=['alias'], name='core_entryv_alias_d23ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['created_at'], name='core_librar_created_48b887_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['title'], name='core_librar_title_998fa6_idx'),
        ),
        migrations.AddField(
            model_name='libraryevent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.libraryitem'),
        ),
        migrations.AddField(
            model_name='libraryevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.librarycategory'),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['event_type'], name='core_librar_event_t_ced945_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['created_at'], name='core_librar_created_dab1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='librarysubmission',
            index=models.Index(fields=['status'], name='core_librar_status_7abb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='librarysubmission',
            index=models.Index(fields=['created_at'], name='core_librar_created_618a31_idx'),
        ),
    ]
