# Generated by Django 5.2.7 on 2025-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libraryevent_librarysubmission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entryvariant',
            unique_together={('entry', 'alias')},
        ),
        migrations.AddIndex(
            model_name='librarycategory',
            index=models.Index(fields=['slug'], name='core_librar_slug_ff2760_idx'),
        ),
    ]
