# Generated by Django 5.2.7 on 2025-11-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Import Job', 'verbose_name_plural': 'Import Jobs'},
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dictionary', 'Dictionary'), ('library', 'Library')], db_index=True, max_length=20)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('has_results', models.BooleanField(default=False)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query Log',
                'verbose_name_plural': 'Search Query Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'has_results'], name='core_search_source_2c3bd4_idx'), models.Index(fields=['created_at'], name='core_search_created_021fa5_idx')],
            },
        ),
    ]
