# Generated by Django 5.2.7 on 2025-11-13 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_importjob_options_searchquerylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['lemma']},
        ),
        migrations.AlterModelOptions(
            name='entryvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='librarycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Library categories'},
        ),
        migrations.AlterModelOptions(
            name='libraryevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='librarysubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='searchquerylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='dictionaryentry',
            name='core_dictio_updated_7f3a0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='librarycategory',
            name='core_librar_slug_ff2760_idx',
        ),
        migrations.RemoveIndex(
            model_name='libraryevent',
            name='core_librar_created_dab1fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='libraryitem',
            name='core_librar_created_48b887_idx',
        ),
        migrations.RemoveIndex(
            model_name='libraryitem',
            name='core_librar_title_998fa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='librarysubmission',
            name='core_librar_created_618a31_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquerylog',
            name='core_search_source_2c3bd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquerylog',
            name='core_search_created_021fa5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='entryvariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='libraryevent',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='librarysubmission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='librarysubmission',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='librarysubmission',
            name='submitter',
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('article', 'Article'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='source_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_item', to='core.librarysubmission'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_library_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librarysubmission',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='gloss_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='gloss_ll',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='lemma',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entryvariant',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='failed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='success_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='librarycategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libraryevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('complete', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libraryevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.librarycategory'),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarysubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='librarysubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarysubmission',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='results_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['-created_at'], name='core_import_created_87e65c_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryevent',
            index=models.Index(fields=['-created_at'], name='core_librar_created_5c6d60_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['-created_at'], name='core_librar_created_679430_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['is_published'], name='core_librar_is_publ_944347_idx'),
        ),
        migrations.AddIndex(
            model_name='librarysubmission',
            index=models.Index(fields=['-created_at'], name='core_librar_created_062a66_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['-created_at'], name='core_search_created_29af60_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['source'], name='core_search_source_14f387_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['has_results'], name='core_search_has_res_c1cbb6_idx'),
        ),
    ]
